### ISSUE TITLE
Response Issues

### ISSUE THREAD

**Issue by AravindRohit** [Soulter/hugging-chat-api#142] opened 2023-11-21 09:34 UTC
Define recursive function in python? reply within 2 sentences  

if we use this in query it is not giving the response same thing is replying not giving about recursive function

**Comment by AravindRohit** [comment] 2023-11-22 04:14
Now falcon Model response is not generating in UI and In my code

**Comment by Whitelisted1** [comment] 2023-11-22 04:45
> Now falcon Model response is not generating in UI and In my code

If the falcon model is not generating in the HuggingChat UI it means that the problem is originating from the HuggingChat servers, which we are not able to fix

**Comment by AravindRohit** [comment] 2023-11-22 04:50
When it will be fixed

**Comment by Whitelisted1** [comment] 2023-11-22 04:55
I don't know when it will be fixed, and I just confirmed that it is still not working

**Comment by Whitelisted1** [comment] 2023-11-22 18:03
@AravindRohit This is not the correct place to see when it will be working again. You might be able to find more information on the [chat-ui discussion page](https://huggingface.co/spaces/huggingchat/chat-ui/discussions) on HuggingFace's website, though

**Closed** 2024-01-30 01:26 UTC
Labels: no-issue-activity
